name: money_tracker
description: "A way to track your Expense"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 3.4.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

 